### ISSUE TITLE
Unable to delete tokens...

### ISSUE THREAD

**Issue by kerns** [infanion-plugins/dynamic-email-template-pro#1]
I was just testing with Craft 3.7 and noticed that my tokens cannot be deleted.

Deleting a token takes me to a blank page. Hitting the back button throws a driver error, and the token remains.

**Comment by Infanion-Admin** [comment]
Hey @kerns can you please provide more details on the issue and also the database you are using and what is the version of database

**Comment by kerns** [comment]
```
PHP version 8.0.7
MySQL 8.0.25
Craft Pro 3.7.10
```

**Comment by Infanion-Admin** [comment]
Hey @kerns  we have released fixes for token delete issue, please check latest version 2.0.0
